// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StudentCrud.Models;

public partial class Department
{
    public int Dept_Id { get; set; }

    public string Dept_Name { get; set; }

    public string Dept_Desc { get; set; }

    public string Dept_Location { get; set; }

    public int? Dept_Manager { get; set; }

    public DateTime? Manager_hiredate { get; set; }

    public virtual Instructor Dept_ManagerNavigation { get; set; }

    public virtual ICollection<Instructor> Instructors { get; set; } = new List<Instructor>();

    public virtual ICollection<Student> Students { get; set; } = new List<Student>();
}