// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StudentCrud.Models;

public partial class Instructor
{
    public int Ins_Id { get; set; }

    public string Ins_Name { get; set; }

    public string Ins_Degree { get; set; }

    public decimal? Salary { get; set; }

    public int? Dept_Id { get; set; }

    public virtual ICollection<Department> Departments { get; set; } = new List<Department>();

    public virtual Department Dept { get; set; }

    public virtual ICollection<Ins_Course> Ins_Courses { get; set; } = new List<Ins_Course>();
}